# Generated by Django 3.2.12 on 2022-03-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='introduction',
        ),
    ]
